format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
${custom.kubeselect}\
$line_break\
$status\
$shell\
$character"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the newline at the start of the prompt
add_newline = false

[gcloud]
disabled = true

[custom.kubeselect]
when = "true"
style = "bold blue"
format = "[($output)]($style)"
