theme = "dracula"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "backlight"

[[block]]
block = "sound"

[[block]]
block = "custom"
command = "echo \uf030" # assumes fontawesome icons
on_click = "$HOME/.flameshot"
interval = "once"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"

[[block]]
block = "custom"
command = "echo \uf011" # assumes fontawesome icons
on_click = "~/.config/i3/scripts/powermenu.sh"
interval = "once"
